name = "GamersMiddled"
author = "Gamers"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b385a645910883edc479116eeadb36c489b01c8f6e637791558975a032dc96fa"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"

[options]
no-internal-hashes = "true"
