name = "GamersMiddled"
author = "Gamers"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96218b5eb4364614bee07eb39eafe77b94a673b222cb8b9466e77f637e186eb0"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
