name = "GamersMiddled"
author = "Gamers"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dbcf0d2890e9f19fe32b118230278a36f7657709035870f7f4a9ed8e21bbefb"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
